name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Updated submodules"
          git push
